<?php

return [
    'groups' => [
        'public' => [
            'login', 'login.otp', 'login.otp.verify', 'login.otp.resend', 'register', 'password.request', 'password.email', 'password.otp', 'password.otp.verify', 'password.otp.resend', 'password.reset', 'password.store', 'password.update', 'password.confirm', 'otp.send', 'otp.verify',
            'courses.index', 'courses.show', 'cart.index', 'cart.add', 'cart.remove', 'cart.clear',
            'blogs.index', 'blogs.show', 'language.switch', 'api.gemini.chat', 'logout', 'auth.google', 'auth.google.callback',
        ],
        'student' => [
            'login', 'login.otp', 'login.otp.verify', 'login.otp.resend', 'register', 'password.request', 'password.email', 'password.otp', 'password.otp.verify', 'password.otp.resend', 'password.reset', 'password.store', 'password.update', 'password.confirm', 'otp.send', 'otp.verify',
            'courses.index', 'courses.show', 'cart.index', 'cart.add', 'cart.remove', 'cart.clear',
            'blogs.index', 'blogs.show', 'language.switch', 'api.gemini.chat', 'logout', 'auth.google', 'auth.google.callback',
            'dashboard', 'dashboard.enrolled-courses', 'dashboard.learning-progress', 'dashboard.reviews',
            'dashboard.quiz-attempts', 'dashboard.wishlist', 'dashboard.order-history', 'dashboard.qa',
            'wishlist.toggle', 'reviews.store', 'reviews.destroy', 'profile.edit', 'profile.update',
            'profile.destroy', 'profile.photo.update', 'profile.photo.destroy',
            'instructor.profile.setup', 'instructor.profile.store', 'payment.checkout', 'payment.mock-complete',
            'payment.cancel', 'cart.checkout', 'cart.checkout-page', 'checkout.resume', 'orders.invoice',
            'courses.learn', 'courses.lessons.content', 'courses.lessons.complete', 'courses.quizzes.complete',
            'courses.lessons.log-progress', 'notifications.read', 'notifications.read-all',
            'discussions.lesson', 'discussions.store', 'discussions.resolve', 'courses.certificate',
            'courses.certificates.index', 'courses.certificates.claim', 'certificates.show', 'modules.certificate.download',
            'assessments.show-student', 'assessments.start', 'attempts.submit',
            'payment.validate-coupon', 'billing.suspended', 'verification.send',
        ],
        'instructor' => [
            // Student base
            'login', 'login.otp', 'login.otp.verify', 'login.otp.resend', 'register', 'password.request', 'password.email', 'password.otp', 'password.otp.verify', 'password.otp.resend', 'password.reset', 'password.store', 'password.update', 'password.confirm', 'otp.send', 'otp.verify',
            'courses.index', 'courses.show', 'cart.index', 'cart.add', 'cart.remove', 'cart.clear',
            'blogs.index', 'blogs.show', 'language.switch', 'api.gemini.chat', 'logout', 'auth.google', 'auth.google.callback',
            'dashboard', 'dashboard.enrolled-courses', 'dashboard.learning-progress', 'dashboard.reviews',
            'dashboard.quiz-attempts', 'dashboard.wishlist', 'dashboard.order-history', 'dashboard.qa',
            'wishlist.toggle', 'reviews.store', 'reviews.destroy', 'profile.edit', 'profile.update',
            'profile.destroy', 'profile.photo.update', 'profile.photo.destroy',
            'instructor.profile.setup', 'instructor.profile.store', 'payment.checkout', 'payment.mock-complete',
            'payment.cancel', 'cart.checkout', 'cart.checkout-page', 'checkout.resume', 'orders.invoice',
            'courses.learn', 'courses.lessons.content', 'courses.lessons.complete', 'courses.quizzes.complete',
            'courses.lessons.log-progress', 'notifications.read', 'notifications.read-all',
            'discussions.lesson', 'discussions.store', 'discussions.resolve', 'courses.certificate',
            'courses.certificates.index', 'courses.certificates.claim', 'certificates.show', 'modules.certificate.download',
            'assessments.show-student', 'assessments.start', 'attempts.submit',
            'payment.validate-coupon', 'billing.suspended', 'verification.send',
            // Instructor specific
            'course-builder.index', 'course-builder.metadata', 'course-builder.store', 'course-builder.build', 'course-builder.update', 'course-builder.destroy', 'course-builder.import',
            'course-builder.modules.store', 'course-builder.modules.update', 'course-builder.modules.destroy',
            'course-builder.lessons.store', 'course-builder.lessons.update', 'course-builder.lessons.destroy',
            'course-builder.quizzes.store', 'course-builder.quizzes.update', 'course-builder.quizzes.destroy',
            'course-builder.questions.store', 'course-builder.questions.update', 'course-builder.questions.destroy',
            'course-builder.assessments.store', 'course-builder.assessments.bulk-store', 'course-builder.assessments.questions.store', 'course-builder.assessments.questions.update', 'course-builder.assessments.questions.destroy',
            'course-builder.certificates.store', 'course-builder.certificates.destroy',
            'bundle-builder.index', 'bundle-builder.store', 'bundle-builder.edit', 'bundle-builder.update', 'bundle-builder.destroy',
            'dashboard.live-class', 'dashboard.live-class.update-schedule', 'live-classes.store', 'live-classes.update', 'live-classes.destroy',
            'dashboard.withdrawals', 'dashboard.withdrawals.store', 'dashboard.payment-profile.store',
            'dashboard.qna',
            'blogs.store', 'blogs.update', 'blogs.destroy',
            'dashboard.settings.blog', 'dashboard.settings.blog.update', 'dashboard.settings.blog.upload-image',
            // Gifting & Reports
            'dashboard.students.search', 'dashboard.courses.gift', 'dashboard.reports.exam', 'assessments.analytics',
        ],
        'admin' => [
            // Instructor base
            'login', 'login.otp', 'login.otp.verify', 'login.otp.resend', 'register', 'password.request', 'password.email', 'password.otp', 'password.otp.verify', 'password.otp.resend', 'password.reset', 'password.store', 'password.update', 'password.confirm', 'otp.send', 'otp.verify',
            'courses.index', 'courses.show', 'cart.index', 'cart.add', 'cart.remove', 'cart.clear',
            'blogs.index', 'blogs.show', 'language.switch', 'api.gemini.chat', 'logout', 'auth.google', 'auth.google.callback',
            'dashboard', 'dashboard.enrolled-courses', 'dashboard.learning-progress', 'dashboard.reviews',
            'dashboard.quiz-attempts', 'dashboard.wishlist', 'dashboard.order-history', 'dashboard.qa',
            'wishlist.toggle', 'reviews.store', 'reviews.destroy', 'profile.edit', 'profile.update',
            'profile.destroy', 'profile.photo.update', 'profile.photo.destroy',
            'instructor.profile.setup', 'instructor.profile.store', 'payment.checkout', 'payment.mock-complete',
            'payment.cancel', 'cart.checkout', 'cart.checkout-page', 'checkout.resume', 'orders.invoice',
            'courses.learn', 'courses.lessons.content', 'courses.lessons.complete', 'courses.quizzes.complete',
            'courses.lessons.log-progress', 'notifications.read', 'notifications.read-all',
            'discussions.lesson', 'discussions.store', 'discussions.resolve', 'courses.certificate',
            'courses.certificates.index', 'courses.certificates.claim', 'certificates.show', 'modules.certificate.download',
            'assessments.show-student', 'assessments.start', 'attempts.submit',
            'payment.validate-coupon', 'billing.suspended', 'verification.send',
            'course-builder.index', 'course-builder.metadata', 'course-builder.store', 'course-builder.build', 'course-builder.update', 'course-builder.destroy', 'course-builder.import',
            'course-builder.modules.store', 'course-builder.modules.update', 'course-builder.modules.destroy',
            'course-builder.lessons.store', 'course-builder.lessons.update', 'course-builder.lessons.destroy',
            'course-builder.quizzes.store', 'course-builder.quizzes.update', 'course-builder.quizzes.destroy',
            'course-builder.questions.store', 'course-builder.questions.update', 'course-builder.questions.destroy',
            'course-builder.assessments.store', 'course-builder.assessments.bulk-store', 'course-builder.assessments.questions.store', 'course-builder.assessments.questions.update', 'course-builder.assessments.questions.destroy',
            'course-builder.certificates.store', 'course-builder.certificates.destroy',
            'bundle-builder.index', 'bundle-builder.store', 'bundle-builder.edit', 'bundle-builder.update', 'bundle-builder.destroy',
            'dashboard.live-class', 'dashboard.live-class.update-schedule', 'live-classes.store', 'live-classes.update', 'live-classes.destroy',
            'dashboard.withdrawals', 'dashboard.withdrawals.store', 'dashboard.payment-profile.store',
            'dashboard.qna',
            'blogs.store', 'blogs.update', 'blogs.destroy',
            'dashboard.settings.blog', 'dashboard.settings.blog.update', 'dashboard.settings.blog.upload-image',
            // Gifting & Reports
            'dashboard.students.search', 'dashboard.courses.gift', 'dashboard.reports.exam', 'assessments.analytics',
            // Admin specific
            'dashboard.users.manage', 'dashboard.users.approve', 'dashboard.users.reject', 'dashboard.users.role', 'dashboard.users.export',
            'dashboard.users.store', 'dashboard.users.settings.update', 'dashboard.users.destroy', 'dashboard.users.restore',
            'dashboard.settings', 'dashboard.settings.update',
            'dashboard.admin.withdrawals', 'dashboard.admin.withdrawals.complete', 'dashboard.admin.withdrawals.reject',
            'dashboard.settings.withdrawal-methods', 'dashboard.settings.withdrawal-methods.store', 'dashboard.settings.withdrawal-methods.update', 'dashboard.settings.withdrawal-methods.destroy',
            'dashboard.ecommerce.analytics', 'dashboard.ecommerce.coupons', 'dashboard.ecommerce.coupons.store', 'dashboard.ecommerce.coupons.update', 'dashboard.ecommerce.coupons.destroy', 'dashboard.ecommerce.settings', 'dashboard.ecommerce.settings.update',
            'dashboard.settings.course-builder', 'dashboard.settings.course-builder.categories.store', 'dashboard.settings.course-builder.categories.update', 'dashboard.settings.course-builder.categories.destroy',
            'dashboard.settings.course-builder.tags.store', 'dashboard.settings.course-builder.tags.update', 'dashboard.settings.course-builder.tags.destroy',
            'dashboard.settings.course-builder.download-template', 'dashboard.settings.course-builder.import', 'dashboard.settings.course-builder.courses',
            'dashboard.settings.course-builder.download-quiz-template', 'dashboard.settings.course-builder.import-quiz',
            'dashboard.settings.course-builder.test-builder.update', 'dashboard.settings.course-builder.user-management.update',
            'blogs.approve', 'dashboard.settings.blog.approve-settings', 'dashboard.settings.blog.reject-settings', 'notifications.test-trigger',
        ],
    ],
];
